# Properties für Profil "dev"
application:
  cors:
    enabled: true
    allowed-origins: '*.swagger.io,test'
  initialization:
    enabled: true
spring:
  datasource:
    url: jdbc:h2:./.local-db/customers
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true
